"""empty message

Revision ID: f3d52f0bc77f
Revises: 
Create Date: 2019-05-18 11:00:09.329527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3d52f0bc77f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_map', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.add_column('user_chat_information', sa.Column('recv_information', sa.Text(), nullable=True))
    op.drop_column('user_chat_information', 'recv_infornation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat_information', sa.Column('recv_infornation', mysql.TEXT(), nullable=True))
    op.drop_column('user_chat_information', 'recv_information')
    op.alter_column('key_map', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
